# azure-pipelines.yml
trigger: none

parameters:
  - name: "ENVIRONMENT"
    displayName: "Environment"
    type: string
    values:
      - "dev"
      - "uat"
    default: "uat"
  - name: "TEST_TYPE"
    displayName: "Test type"
    type: string
    values:
      - "constant"
      - "load"
      - "spike"
      - "stress"
    default: "constant"
  - name: "SCRIPT"
    displayName: "Script name"
    type: string
    values:
      - receipt_processor
      - receipt_flow_simulation
    default: "receipt_processor"
  - name: "DB_NAME"
    displayName: "DB name"
    type: string
    values:
      - pagopa_receipt_pdf_datastorek6

variables:
  ${{ if eq(parameters['ENVIRONMENT'], 'dev') }}:
    receiptCosmosSubscriptionKey: "$(DEV_RECEIPT_COSMOS_DB_SUBSCRIPTION_KEY)"
    bizEventCosmosSubscriptionKey: "$(DEV_BIZEVENT_COSMOS_DB_SUBSCRIPTION_KEY)"
    blobStorageConnectionString: "$(DEV_BLOB_STORAGE_CONNECTION_STRING)"
    poolImage: "pagopa-dev-loadtest-linux"
  ${{ if eq(parameters['ENVIRONMENT'], 'uat') }}:
    receiptCosmosSubscriptionKey: "$(UAT_RECEIPT_COSMOS_DB_SUBSCRIPTION_KEY)"
    bizEventCosmosSubscriptionKey: "$(UAT_BIZEVENT_COSMOS_DB_SUBSCRIPTION_KEY)"
    blobStorageConnectionString: "$(UAT_BLOB_STORAGE_CONNECTION_STRING)"
    poolImage: "pagopa-uat-loadtest-linux"

pool:
  name: $(poolImage)

steps:
  - script: |
      cd ./performance-test/src
      docker pull grafana/k6
    displayName: Pull k6 image
  - script: |
      cd ./performance-test
      sh ./run_performance_test.sh ${{ parameters.ENVIRONMENT }} ${{ parameters.TEST_TYPE }} ${{ parameters.SCRIPT }} ${{ parameters.DB_NAME }} $BIZEVENT_COSMOS_SUBSCRIPTION_KEY $RECEIPT_COSMOS_SUBSCRIPTION_KEY
    displayName: Run k6 ${{ parameters.SCRIPT }} on ${{ parameters.ENVIRONMENT }}
    env:
      RECEIPT_COSMOS_SUBSCRIPTION_KEY: ${{ variables.receiptCosmosSubscriptionKey }}
      BIZEVENT_COSMOS_SUBSCRIPTION_KEY: ${{ variables.bizEventCosmosSubscriptionKey }}
  - script: |
      cd ./performance-test/src
      docker build -f ./DockerfileReview -t exec-node .
      docker run --rm --name initToRunk6 \
      -e RECEIPT_COSMOS_SUBSCRIPTION_KEY=${RECEIPT_COSMOS_SUBSCRIPTION_KEY} \
      -e ENVIRONMENT_STRING="${ENVIRONMENT_STRING}" \
      exec-node     
    displayName: Run Receipts Timestamp Review
    condition: eq(parameters['SCRIPT'], 'receipt_flow_simulation')
    env:
      RECEIPT_COSMOS_SUBSCRIPTION_KEY: ${{ variables.receiptCosmosSubscriptionKey }}
  - script: |
      cd ./performance-test/src
      docker build -f ./DockerfileTeardown -t exec-node .
      docker run --rm --name initToRunk6 \
      -e BLOB_STORAGE_CONN_STRING=${BLOB_STORAGE_CONN_STRING} \
      -e RECEIPT_COSMOS_SUBSCRIPTION_KEY=${RECEIPT_COSMOS_SUBSCRIPTION_KEY} \
      -e BIZEVENT_COSMOS_SUBSCRIPTION_KEY=${BIZEVENT_COSMOS_SUBSCRIPTION_KEY} \
      -e ENVIRONMENT_STRING="${ENVIRONMENT_STRING}" \
      exec-node     
    displayName: Run Receipts Teardown
    condition: eq(parameters['SCRIPT'], 'receipt_flow_simulation')
    env:
      RECEIPT_COSMOS_SUBSCRIPTION_KEY: ${{ variables.receiptCosmosSubscriptionKey }}
      BIZEVENT_COSMOS_SUBSCRIPTION_KEY: ${{ variables.bizEventCosmosSubscriptionKey }}
      BLOB_STORAGE_CONN_STRING: ${{ variables.blobStorageConnectionString }}
      
