microservice-chart:
  namespace: "receipts"
  nameOverride: ""
  fullnameOverride: ""
  image:
    repository: ghcr.io/pagopa/pagopa-receipt-pdf-datastore
    tag: "0.1.4"
    pullPolicy: Always
  # https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script.WebHost/Controllers/HostController.cs
  livenessProbe:
    httpGet:
      path: /info
      port: 80
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /info
      port: 80
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 10
  deployment:
    create: true
  service:
    create: true
    type: ClusterIP
    port: 80
  ingress:
    create: true
    host: "weuprod.receipts.internal.platform.pagopa.it"
    path: /pagopa-receipt-pdf-datastore/(.*) #
  serviceAccount:
    create: false
    annotations: {}
    name: ""
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
  resources:
    requests:
      memory: "512Mi"
      cpu: "0.25"
    limits:
      memory: "512Mi"
      cpu: "0.25"
  autoscaling:
    enable: true
    minReplica: 3
    maxReplica: 10
    pollingInterval: 10 # seconds
    cooldownPeriod: 50 # seconds
    triggers:
      - type: cpu
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "75"
  envConfig:
    WEBSITE_SITE_NAME: "pagopareceiptpdfdatastore" # required to show cloud role name in application insights
    FUNCTIONS_WORKER_RUNTIME: "java"
    RECEIPT_QUEUE_TOPIC: 'pagopa-p-weu-receipts-queue-receipt-waiting-4-gen'
    COSMOS_RECEIPT_QUEUE_MAX_RETRY: '5'
    PDF_ENGINE_ENDPOINT: 'https://api.prod.platform.pagopa.it/shared/pdf-engine/v1/generate-pdf'
    COSMOS_RECEIPT_SERVICE_ENDPOINT: 'https://pagopa-p-weu-receipts-ds-cosmos-account.documents.azure.com:443/'
    COSMOS_RECEIPT_DB_NAME: 'db'
    COSMOS_RECEIPT_CONTAINER_NAME: 'receipts'
    PDF_BLOB_STORAGE_ENDPOINT: 'https://pagopapweureceiptsfnsa.blob.core.windows.net'
    PDF_BLOB_STORAGE_CONTAINER: 'pagopa-p-weu-receipts-azure-blob-receipt-st-attach'
  envSecret:
    APPLICATIONINSIGHTS_CONNECTION_STRING: 'ai-p-connection-string'
    PDF_BLOB_STORAGE_CONN_STRING: 'pdf-blob-storage-p-connection-string'
    COSMOS_RECEIPTS_CONN_STRING: 'cosmos-receipt-p-connection-string'
    RECEIPT_QUEUE_CONN_STRING: 'receipt-queue-p-connection-string'
    COSMOS_BIZ_EVENT_CONN_STRING: 'cosmos-biz-event-p-connection-string'
    OCP_APIM_SUBSCRIPTION_KEY: 'shared-apim-p-subscription-key'
    COSMOS_RECEIPT_KEY: 'cosmos-receipt-p-key'
  keyvault:
    name: "pagopa-p-receipts-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: {}
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - user
  canaryDelivery:
    create: true
    ingress:
      create: true
      canary:
        type: header
        headerName: X-Canary
        headerValue: canary
        weightPercent: 0
    service:
      create: true
    deployment:
      create: true
      image:
        repository: ghcr.io/pagopa/pagopa-receipt-pdf-datastore
        tag: "0.1.4"
        pullPolicy: Always
      envConfig:
      envSecret:
